title:          "Brendan Ta"
description:    "Dump"
url:            "https://brendanta.com"
baseurl:        ""
author:
  name:         "Brendan Ta"
  avatar:       "/assets/img/borko.png"
  github:       "bwenstar"

markdown: kramdown
theme: null
exclude:
  - .github/
  - node_modules/
  - README.md
